### ISSUE TITLE
Class not found when unmarshalling still exists.

### ISSUE THREAD

**Issue by glidodroid** [rharter/auto-value-parcel#104]
I have resolved #103 issue only by downgrading the auto-value libraries to.
`compile 'com.google.auto.value:auto-value:1.2'`
    `apt 'com.ryanharter.auto.value:auto-value-parcel:0.2.1'`
    `compile 'com.ryanharter.auto.value:auto-value-parcel-adapter:0.2.1'`
```java 
final class AutoValue_AppNavigator_NavigationToken extends $AutoValue_AppNavigator_NavigationToken {
  public static final Parcelable.Creator<AutoValue_AppNavigator_NavigationToken> CREATOR = new Parcelable.Creator<AutoValue_AppNavigator_NavigationToken>() {
    @Override
    public AutoValue_AppNavigator_NavigationToken createFromParcel(Parcel in) {
      ClassLoader cl = AutoValue_AppNavigator_NavigationToken.class.getClassLoader();
      return new AutoValue_AppNavigator_NavigationToken(
          in.readInt(),
          in.readBundle(cl),
          in.readInt() == 0 ? (Parcelable) in.readParcelable(cl) : null
      );
    }
```
Above doesn't produce error.

While I tried to use below dependencies,only with auto-value version change
`compile 'com.google.auto.value:auto-value:1.3'`
    `apt 'com.ryanharter.auto.value:auto-value-parcel:0.2.5'`
    `compile 'com.ryanharter.auto.value:auto-value-parcel-adapter:0.2.5'`
It leads to the error #103 and below is the generated auto-value class.

```java
final class AutoValue_AppNavigator_NavigationToken extends $AutoValue_AppNavigator_NavigationToken {
  public static final Parcelable.Creator<AutoValue_AppNavigator_NavigationToken> CREATOR = new Parcelable.Creator<AutoValue_AppNavigator_NavigationToken>() {
    @Override
    public AutoValue_AppNavigator_NavigationToken createFromParcel(Parcel in) {
      return new AutoValue_AppNavigator_NavigationToken(
          in.readInt(),
          in.readBundle(Bundle.class.getClassLoader()),
          in.readParcelable(Parcelable.class.getClassLoader())
      );
    } 
```

I could see the difference in class loaders. Is the class loader is not identified properly?

**Comment by scottlahay** [comment]
I'm getting a similar problem. With a twist.  Works fine on a MotoPlay running android 6.0.1, Blows up on Samsung Galaxy s3 running 4.4.2 

 E/Parcel: Class not found when unmarshalling: com...data.entities.AutoValue_Offer
                                        java.lang.ClassNotFoundException: com...data.entities.AutoValue_Offer
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.Class.forName(Class.java:251)
                                            at java.lang.Class.forName(Class.java:216)
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2140)
                                            at android.os.Parcel.readParcelable(Parcel.java:2104)
                                            at android.os.Parcel.readValue(Parcel.java:2020)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
                                            at android.os.Bundle.unparcel(Bundle.java:249)
                                            at android.os.Bundle.getString(Bundle.java:1118)
                                            at android.content.Intent.getStringExtra(Intent.java:5145)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1449)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1045)
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4066)
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3960)
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159)
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2641)
                                            at android.os.Binder.execTransact(Binder.java:404)
                                            at dalvik.system.NativeStart.run(Native Method)
                                         Caused by: java.lang.NoClassDefFoundError: com///data/entities/AutoValue_Offer
                                            at java.lang.Class.classForName(Native Method) 
                                            at java.lang.Class.forName(Class.java:251) 
                                            at java.lang.Class.forName(Class.java:216) 
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2140) 
                                            at android.os.Parcel.readParcelable(Parcel.java:2104) 
                                            at android.os.Parcel.readValue(Parcel.java:2020) 
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2321) 
                                            at android.os.Bundle.unparcel(Bundle.java:249) 
                                            at android.os.Bundle.getString(Bundle.java:1118) 
                                            at android.content.Intent.getStringExtra(Intent.java:5145) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1449) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1045) 
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4066) 
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3960) 
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159) 
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2641) 
                                            at android.os.Binder.execTransact(Binder.java:404) 
                                            at dalvik.system.NativeStart.run(Native Method) 
                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com...data.entities.AutoValue_Offer" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                            at java.lang.Class.classForName(Native Method) 
                                            at java.lang.Class.forName(Class.java:251) 
                                            at java.lang.Class.forName(Class.java:216) 
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2140) 
                                            at android.os.Parcel.readParcelable(Parcel.java:2104) 
                                            at android.os.Parcel.readValue(Parcel.java:2020) 
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2321) 
                                            at android.os.Bundle.unparcel(Bundle.java:249) 
                                            at android.os.Bundle.getString(Bundle.java:1118) 
                                            at android.content.Intent.getStringExtra(Intent.java:5145) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1449) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1045) 
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4066) 
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3960) 
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159) 
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2641) 
                                            at android.os.Binder.execTransact(Binder.java:404) 
                                            at dalvik.system.NativeStart.run(Native Method)
