### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Implementing class

### ISSUE THREAD

**Issue by UnknownUntilNow** [rharter/auto-value-parcel#13]
in build.gradle dependencies:

    apt 'com.google.auto.value:auto-value:1.2-SNAPSHOT'
    compile 'com.google.auto.value:auto-value:1.2-SNAPSHOT'
    apt 'com.ryanharter.auto.value:auto-value-parcel:0.2-SNAPSHOT'
I get the following exception on compiling:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
		at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
		at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
		at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
		at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
		at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
		at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
		at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
		at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
		at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
		at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
		at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
		at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
		at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
		at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
		at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
		at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
		at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
		at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
		at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
		at org.gradle.launcher.Main.doAction(Main.java:33)
		at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
		at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
		at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
		at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
		at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
		at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
		at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
	Caused by: java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: Implementing class
		at com.sun.tools.javac.main.Main.compile(Main.java:553)
		at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
		at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
		at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:42)
		at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
		at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
		at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
		at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
		at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
		at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
		at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
		at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
		at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:92)
		at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
		... 47 more
	Caused by: java.lang.IncompatibleClassChangeError: Implementing class
		at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:369)
		at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:141)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
		at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
		at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
		at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
		at com.sun.tools.javac.main.Main.compile(Main.java:523)
		... 66 more
```

**Comment by rharter** [comment]
This is a little difficult while the extension support of AutoValue is in SNAPSHOT, but this can happen when the version of the extension doesn't match the version of AutoValue it was written for.  This shouldn't be an issue anymore after we get some release builds.

For now, simply updating the snapshot dependencies should do the trick (gradle: `gradlew assemble --refresh-dependencies`) or, if it takes me a couple days to catch up with a new release, building the extension yourself and putting it on the classpath should work.
