### ISSUE TITLE
Parcelable.Creator field needs to be public 

### ISSUE THREAD

**Issue by gabrielittner** [rharter/auto-value-parcel#4]
http://developer.android.com/reference/android/os/Parcelable.Creator.html

Otherwise you'll get an exception:
```
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class com.gabrielittner.timetable.notemute.AutoValue_LessonTime
            at android.os.Parcel.readParcelableCreator(Parcel.java:2298)
            at android.os.Parcel.readParcelable(Parcel.java:2239)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getParcelable(Bundle.java:804)
            at android.content.Intent.getParcelableExtra(Intent.java:4850)
```

**Comment by rharter** [comment]
Good catch, not sure how this one got through.  I've updated the 0.2-SNAPSHOT build to include this fix.
