### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by PaulWoitaschek** [rharter/auto-value-parcel#54]
While trying to run the tests almost every test fails. (Except of `acceptsParcelableProperties` and `throwsForNonParcelableProperty`).

Do you have any idea what is going on here?

```java
java.lang.AssertionError: Compilation produced the following errors:

/SOURCE_OUTPUT/test/AutoValue_No.java:7: error: test.AutoValue_No is not abstract and does not override abstract method writeToParcel(android.os.Parcel,int) in android.os.Parcelable
 final class AutoValue_No extends No {
       ^
/SOURCE_OUTPUT/test/AutoValue_Yes.java:7: error: test.AutoValue_Yes is not abstract and does not override abstract method writeToParcel(android.os.Parcel,int) in android.os.Parcelable
 final class AutoValue_Yes extends Yes {
       ^


Generated Files
===============

/SOURCE_OUTPUT/test/AutoValue_Yes.java:

package test;

import javax.annotation.Generated;

@Generated("com.google.auto.value.processor.AutoValueProcessor")
 final class AutoValue_Yes extends Yes {

  private final String name;

  AutoValue_Yes(
      String name) {
    if (name == null) {
      throw new NullPointerException("Null name");
    }
    this.name = name;
  }

  @Override
  public String name() {
    return name;
  }

  @Override
  public String toString() {
    return "Yes{"
        + "name=" + name
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Yes) {
      Yes that = (Yes) o;
      return (this.name.equals(that.name()));
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h = 1;
    h *= 1000003;
    h ^= this.name.hashCode();
    return h;
  }

}


/SOURCE_OUTPUT/test/AutoValue_No.java:

package test;

import javax.annotation.Generated;

@Generated("com.google.auto.value.processor.AutoValueProcessor")
 final class AutoValue_No extends No {

  private final String name;
  private final int describeContents;

  AutoValue_No(
      String name,
      int describeContents) {
    if (name == null) {
      throw new NullPointerException("Null name");
    }
    this.name = name;
    this.describeContents = describeContents;
  }

  @Override
  public String name() {
    return name;
  }

  @Override
  public int describeContents() {
    return describeContents;
  }

  @Override
  public String toString() {
    return "No{"
        + "name=" + name + ", "
        + "describeContents=" + describeContents
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof No) {
      No that = (No) o;
      return (this.name.equals(that.name()))
           && (this.describeContents == that.describeContents());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h = 1;
    h *= 1000003;
    h ^= this.name.hashCode();
    h *= 1000003;
    h ^= this.describeContents;
    return h;
  }

}



	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
	at com.google.testing.compile.JavaSourcesSubject$CompilationClause.compilesWithoutError(JavaSourcesSubject.java:274)
	at com.ryanharter.auto.value.parcel.AutoValueParcelExtensionTest.describeContentsOmittedWhenAlreadyDefined(AutoValueParcelExtensionTest.java:463)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.google.testing.compile.CompilationRule$1$1.process(CompilationRule.java:83)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.google.testing.compile.Compilation.compile(Compilation.java:73)
	at com.google.testing.compile.CompilationRule$1.evaluate(CompilationRule.java:59)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by naturalwarren** [comment]
I see the same thing.

**Comment by rharter** [comment]
How are you running the tests?  What happens when you run `./gradlew clean test` from the command line? 

I have seen every once in a while IntelliJ getting stuck in a weird state where it doesn't seem to run the extensions.

**Comment by rharter** [comment]
With no comment for several weeks, and the expectation that this is a local issue, I'm closing this.  Please reopen if you think this is a problem with the code.

**Comment by mikemalekzadeh** [comment]
@rharter The extensions are not working in one of my projects in Android Studio. AutoValue classes are generated for my classes but GsonTypeAdapter() method is not in generated classes. I cleaned the project and rebuild it (./gradlew clean) but it did not work. Can you please let me know how i can fix it. I saw on the comment you mentioned "I have seen every once in a while IntelliJ getting stuck in a weird state where it doesn't seem to run the extensions."

Thanks

**Comment by rharter** [comment]
Do you have the static method returning a type adapter.

**Comment by mikemalekzadeh** [comment]
yes, i have, but i am getting compilation issue on this method GsonTypeAdapter(gson)

@AutoValue
public abstract class UserReadiness {

  @SerializedName("topics") public abstract List<UserTopicReadiness> topics();

  public static TypeAdapter<UserReadiness> typeAdapter(Gson gson) {
    return new AutoValue_UserReadiness.GsonTypeAdapter(gson);
  }

}
