### ISSUE TITLE
Unmarshalling unknown type code XXXXX at offset XXXXX

### ISSUE THREAD

**Issue by AcaudalAoudad** [rharter/auto-value-parcel#94]
I have a service defined in an app that takes auto-value objects that implement parcelable using auto-value-parcel defined in an AAR that's crashing with the following exception:

      java.lang.RuntimeException: Parcel android.os.Parcel@420a36e0: Unmarshalling unknown type code 5177414 at offset 224
      at android.os.Parcel.readValue(Parcel.java:2080)
      at android.os.Parcel.readListInternal(Parcel.java:2343)
      at android.os.Parcel.readArrayList(Parcel.java:1703)
      at android.os.Parcel.readValue(Parcel.java:2034)
      at com.realityi.sceaa.shared.logging.AutoValue_Event.<init>(AutoValue_Event.java:49)
      at com.realityi.sceaa.shared.logging.AutoValue_Event.<init>(AutoValue_Event.java:7)
      at com.realityi.sceaa.shared.logging.AutoValue_Event$1.createFromParcel(AutoValue_Event.java:62)
      at com.realityi.sceaa.shared.logging.AutoValue_Event$1.createFromParcel(AutoValue_Event.java:59)
      at android.os.Parcel.readParcelable(Parcel.java:2104)
      at android.os.Parcel.readValue(Parcel.java:2013)
      at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
      at android.os.Bundle.unparcel(Bundle.java:249)
      at android.os.Bundle.getParcelable(Bundle.java:1206)
      at android.content.Intent.getParcelableExtra(Intent.java:4660)
      at com.realityi.bitshuttle.android.deviceconfigurationmanager.logging.LoggingIntentService.onHandleIntent(LoggingIntentService.java:40)

The generated file for my type is [https://gist.github.com/AcaudalAoudad/4ebf63bb3dbe22249c9db5f0c2bfe19f.js](here)

I'm using `Intent.putExtra` and `Intent.getParcelableExtra` to send and receive, could the fact that AutoValue_Event is defined in my AAR be the reason I'm getting this error? When I go through my calls with the debugger after calling `Intent.putExtra` in my AAR library I can immediately call `getParcelableExtra` and get the correct object, the problem doesn't appear until I receive the object in my `Service`, which isn't in the AAR library. I was using AutoParcel earlier, and it seemed to work for this use-case, but wasn't handling null values, so I'm not sure if it might just be something I'm doing wrong on my end.

**Comment by AcaudalAoudad** [comment]
I've really got to start exhausting more options before I open Github issues... turns out AS was pushing old code, a rebuild fixed it.
